<?php $direct = Mage::getModel('tpg/direct'); ?>
<?php $_code = $this->getMethodCode() ?>
<?php $route = $this->getRequest()->getRequestedRouteName(); if($route == 'onestepcheckout'){ $fieldCode = '['.$_code.']'; } else { $fieldCode = ''; } ?>

<?php

if(Mage::getSingleton('customer/session')->isLoggedIn()) {
	$customer = Mage::getSingleton('customer/session')->getCustomer();
	$customerID = $customer->getId();

	$orderPaymentTableName = Mage::getSingleton('core/resource')->getTableName('sales/order_payment');

	$orderCollection = Mage::getModel('sales/order')->getCollection()
		->addFilter('customer_id', $customerID)
		->setOrder('entity_id', 'DESC');
	$orderCollection->getSelect()
		->join(
			array("order_payment" => $orderPaymentTableName),
			"main_table.entity_id=order_payment.entity_id"
		);

	//check if a cross reference was set in any of the previous transactions by this customer
	foreach($orderCollection as $order)
	{
		$crossReference = $order->getLastTransId();
		if(isset($crossReference))
		{
			$cardLastFour = $order->getCcLast4();
			$cardType = $order->getCcType();
			break;
		}
	}
}

?>

<fieldset class="form-list">
	<ul id="payment_form_<?php echo $_code ?>" style="display:none">
		<li>
			<img alt="<?php echo $this->__('PayVector Corporation Logo'); ?>" src="<?php echo $this->getSkinUrl('images/payvector.png'); ?>">
		</li>
<?php
//check if cross reference is set - if so show the choice to use the saved card
if(isset($crossReference)):
?>
		<li>
			<?php if(isset($cardLastFour)): ?>
			<label for="<?php echo $_code; ?>_payment_type_stored"><?php echo $this->__('Use Saved ' . $cardType . ' Card: xxxx-'.$cardLastFour) ?> <span class="required">*</span></label><br/>
			<?php else: ?>
			<label for="<?php echo $_code; ?>_payment_type_stored"><?php echo $this->__('Use Saved ' . $cardType . ' Card') ?> <span class="required">*</span></label><br/>
			<?php endif; ?>
			<input type="radio" title="<?php echo $this->__('Use Saved Card') ?>" id="<?php echo $_code; ?>_payment_type_stored" name="payment<?php echo $fieldCode; ?>[payment_type]" value="stored_card" checked/>
		</li>
		<li>
			<label for="<?php echo $_code; ?>_payment_type_new"><?php echo $this->__('Or enter new card details') ?> <span class="required">*</span></label><br/>
			<input type="radio" title="<?php echo $this->__('Or enter new card details') ?>" id="<?php echo $_code; ?>_payment_type_new" name="payment<?php echo $fieldCode; ?>[payment_type]" value="new_card"/>
		</li>
<?php else: ?>
		<input type="hidden" id="<?php echo $_code; ?>_payment_type" name="payment<?php echo $fieldCode; ?>[payment_type]" value="new_card"/>
<?php endif; ?>

<?php
//check if we're using the hosted payment form - if so then inform the user they will be transferred to input their card details
if ($direct->getConfigData('mode') == PayVector_Tpg_Model_Source_PaymentMode::PAYMENT_MODE_HOSTED_PAYMENT_FORM):
?>
		<li class="new_card">
			<?php echo $this->__('You will be redirected to a secure page where you can complete your payment.') ?>
		</li>
		<li class='new_card notice-msg'>
			<?php echo $this->__('Please do not attempt to click the "BACK" button in your browser once you were redirected to the secure payment page to complete your payment. If you need to change your order you can do it before placing your order.') ?>
		</li>
<?php
//else if we're using the Direct/API method then take card details here
else:
?>
		<li class="new_card">
			<div class="input-box">
				<label for="<?php echo $_code; ?>_cc_owner"><?php echo $this->__('Name On Card') ?> <span class="required">*</span></label><br/>
				<input type="text" title="<?php echo $this->__('Name On Card') ?>" class="input-text required-entry validate-length maximum-length-100" id="<?php echo $_code; ?>_cc_owner" name="payment<?php echo $fieldCode; ?>[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>"/>
			</div>
		</li>
		<li class="new_card">
			<div class="input-box">
				<label for="<?php echo $_code; ?>_cc_number"><?php echo $this->__('Card Number') ?> <span class="required">*</span></label><br/>
				<input type="text" id="<?php echo $_code; ?>_cc_number" name="payment<?php echo $fieldCode; ?>[cc_number]" title="<?php echo $this->__('Card Number') ?>" class="input-text required-entry validate-digits validate-length maximum-length-20 validate-cc-number" value=""/>
			</div>
		</li>
		<li class="new_card">
			<label for="<?php echo $_code; ?>_cc_ss_start_month"><?php echo $this->__('Start Date') ?></label><br />
			<div class="input-box">
				<div class="v-fix">
					<select id="<?php echo $_code; ?>_cc_ss_start_month" name="payment<?php echo $fieldCode; ?>[cc_ss_start_month]" class="month">
						<option value=""></option>
						<?php $_ccStartMonth = $this->getInfoData('cc_ss_start_month') ?>
						<?php foreach ($this->getCcStartMonths() as $k=>$v): ?>
							<option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccStartMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
						<?php endforeach ?>
					</select>
				</div>
				<div class="v-fix" style="padding-left:5px;">
					<select id="<?php echo $_code ?>_cc_ss_start_year" name="payment<?php echo $fieldCode; ?>[cc_ss_start_year]" class="year">
						<option value=""></option>
						<?php $_ccStartYear = $this->getInfoData('cc_ss_start_year') ?>
						<?php foreach ($this->getCcStartYears() as $k=>$v): ?>
							<option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccStartYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
						<?php endforeach ?>
					</select>
				</div>
			</div>
		</li>
		<li class="new_card">
			<label for="<?php echo $_code; ?>_expiration"><?php echo $this->__('Expiry Date') ?> <span class="required">*</span></label><br/>
			<div class="input-box">
				<div class="v-fix">
				<select id="<?php echo $_code; ?>_expiration" name="payment<?php echo $fieldCode; ?>[cc_exp_month]" class="month validate-cc-exp required-entry">
				<?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
				<?php foreach ($this->getCcMonths() as $k=>$v): ?>
					<option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
				<?php endforeach ?>
				</select>
				</div>

				<div class="v-fix" style="padding-left:5px;">
				<?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
				<select id="<?php echo $_code; ?>_expiration_yr" name="payment<?php echo $fieldCode; ?>[cc_exp_year]" class="year required-entry">
				<?php foreach ($this->getCcYears() as $k=>$v): ?>
					<option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
				<?php endforeach ?>
				</select>
				</div>
			</div>
		</li>
		<li class="new_card">
			<div class="input-box">
				<label for="<?php echo $_code; ?>_cc_ss_issue"><?php echo $this->__('Issue Number') ?></label><br />
				<div class="v-fix"><input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text validate-digits validate-length maximum-length-2" style="width:50px;" id="<?php echo $_code ?>_cc_ss_issue" name="payment<?php echo $fieldCode; ?>[cc_ss_issue]" value="" /></div>
			</div>
		</li>
<?php endif; ?>
		<li class="cvv">
			<div class="input-box">
				<label for="<?php echo $_code; ?>_cc_cid"><?php echo $this->__('CV2') ?> <span class="required">*</span></label><br/>
				<div class="v-fix"><input type="text" title="<?php echo $this->__('CV2') ?>" class="input-text required-entry validate-digits validate-length minimum-length-3 maximum-length-4" style="width:50px;" id="<?php echo $_code; ?>_cc_cid" name="payment<?php echo $fieldCode; ?>[cc_cid]" value=""/></div>
				&nbsp;
				<a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
			</div>
		</li>
	</ul>
</fieldset>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
//<![CDATA[
	//ensure jQuery.noConflict is only run once
	if(typeof ranNoConflict === 'undefined' || ranNoConflict !== true)
	{
		jQuery_1_11 = jQuery.noConflict(true);
	}
	ranNoConflict = true;

	jQuery_1_11(document).ready(function()
	{
		var paymentType = "HPF";
		if (jQuery_1_11('#<?php echo $_code; ?>_cc_number').length > 0) {
			//input for taking cc number exists therefore we're using the direct method
			paymentType = "DIRECT";
		}

		var $paymentType = jQuery_1_11('input[name="payment<?php echo $fieldCode; ?>[payment_type]"]');
		var $newCardRadio = jQuery_1_11('#<?php echo $_code; ?>_payment_type_new');
		var $newCardInput = jQuery_1_11('.new_card');
		var $cvvInput = jQuery_1_11('.cvv');

		if(jQuery_1_11('input[name="payment<?php echo $fieldCode; ?>[payment_type]"]:checked').val() === "stored_card")
		{
			$newCardInput.hide();
		}

		$paymentType.click(function()
		{
			if($newCardRadio.is(':checked'))
			{
				$newCardInput.show();
				if(paymentType === "HPF")
				{
					$cvvInput.hide();
				}
			}
			else
			{
				$newCardInput.hide();
				if(paymentType === "HPF")
				{
					$cvvInput.show();
				}
			}
		});
	});
//]]>
</script>